# Generated by Django 4.0 on 2022-05-18 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userpermission'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpermission',
            table=None,
        ),
    ]
