# Generated by Django 4.0 on 2022-05-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_userpermission_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpermission',
            table='user_permission',
        ),
    ]
