# Generated by Django 4.0 on 2022-05-21 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_projectuserwork_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lograting',
            name='detail_rating_id',
        ),
        migrations.AddField(
            model_name='lograting',
            name='rating_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.rating'),
        ),
        migrations.AddField(
            model_name='rating',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='lograting',
            name='action',
            field=models.CharField(default='CREATE', max_length=50),
        ),
        migrations.AlterField(
            model_name='lograting',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_column='modified_at', null=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_column='modified_at', null=True, verbose_name='Updated at'),
        ),
        migrations.DeleteModel(
            name='DetailRating',
        ),
    ]
