# Generated by Django 4.0 on 2022-05-21 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_lograting_detail_rating_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lograting',
            name='user_id_rated',
        ),
    ]
