# Generated by Django 4.0 on 2022-05-23 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_lograting_user_id_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='lograting',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
