# Generated by Django 4.0 on 2022-05-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_project_project_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lograting',
            name='score',
            field=models.CharField(default=0, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
