# Generated by Django 4.0 on 2022-05-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_lograting_score_alter_rating_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='session_rating',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
