# Generated by Django 4.0.2 on 2022-02-28 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_detailrating_project_rating_projectuserwork_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='project',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
