# Generated by Django 4.0.2 on 2022-03-03 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_rename_skill_name_skill_name_alter_project_date_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lograting',
            name='action',
            field=models.CharField(default='update', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lograting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lograting',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lograting',
            name='user_id_assessor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_assessor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lograting',
            name='user_id_rated',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_rated', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
