# Generated by Django 4.0.2 on 2022-03-03 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_lograting_action_lograting_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectuserwork',
            old_name='archieves',
            new_name='achieves',
        ),
        migrations.AlterField(
            model_name='lograting',
            name='action',
            field=models.CharField(default='update', max_length=50),
        ),
        migrations.AlterField(
            model_name='lograting',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='lograting',
            name='user_id_assessor',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assessor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lograting',
            name='user_id_rated',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_rated', to=settings.AUTH_USER_MODEL),
        ),
    ]
