# Generated by Django 4.0.2 on 2022-03-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_archieves_projectuserwork_achieves_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lograting',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
