# Generated by Django 4.0.2 on 2022-03-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_lograting_update_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lograting',
            old_name='update_at',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='lograting',
            name='updated_by',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
