# Generated by Django 4.0 on 2022-03-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rolepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=100)),
                ('role_id', models.IntegerField()),
                ('role_name', models.CharField(max_length=100)),
                ('permission_id', models.IntegerField()),
                ('permission_code_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'UserRolePermission',
                'managed': False,
            },
        ),
    ]
