# Generated by Django 4.0 on 2022-03-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_userrolepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrolepermission',
            options={},
        ),
    ]
