# Generated by Django 4.0 on 2022-03-16 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_userrolepermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrolepermission',
            options={'managed': False},
        ),
    ]
