# Generated by Django 4.0 on 2022-03-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_userrolepermission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrolepermission',
            options={},
        ),
    ]
