# Generated by Django 4.0 on 2022-03-21 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_tempuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TempUser',
        ),
    ]
