

USER_POSITION_ROLE_DIRECTOR = 1
USER_POSITION_ROLE_LEADER = 2
USER_POSITION_ROLE_MANAGER = 3
USER_POSITION_ROLE_EMPLOYEE = 4

USER_LEVEL_FRESHER = 1
USER_LEVEL_JUNIOR = 2
USER_LEVEL_MIDDLE = 3
USER_LEVEL_SENIOR = 4
USER_LEVEL_PRINCIPLE = 5

